main: ${project.groupId}.${project.artifactId}
name: ${project.name}
api-version: 1.16
version: ${project.version}
description: ${project.description}

commands:
  tpa:
    usage: </tpa> <name>
    description: Use this command to teleport to a player after requesting it.
    permission: teleportation.tpa
    permission-message: You don't have permission to use this command.
  tpaHere:
    usage: </tpaHere> <name>
    description: Use this command to teleport a player to you after requesting it.
    permission: teleportation.tpa
    permission-message: You don't have permission to use this command..
  setHome:
    usage: </setHome> <name> 
    description: Use this command to create a personal warp point.
    permission: teleportation.sethome
    permission-message: You don't have permission to use this command.
  home:
    usage: </home> <name>
    description: Use this command to teleport to your personal warp point.
    permission: teleportation.home
    permission-message: You don't have permission to use this command.
  deleteHome:
    usage: </home> <name> 
    description: Use this command to destroy your personal warp point.
    permission: teleportation.deleteHome
    permission-message: You don't have permission to use this command.
  viewHomes:
    usage: </viewHomes> <name>
    description: Use this command to view the personal warp of other players.
    permission: teleportation.viewHomes
    permission-message: You don't have permission to use this command.
  homes:
    usage: </viewHomes>
    description: Use this command to view your personal warp points.
    permission: teleportation.homes
    permission-message: You don't have permission to use this command.
  setWarp:
    usage: </setWarp> <name>
    description: Use this command create a public warp point.
    permission: teleportation.setWarp
    permission-message: You don't have permission to use this command.
  warp:
    usage: </warp> <name>
    description: Use this command to teleport to a public warp point.
    permission: teleportation.warp
    permission-message: You don't have permission to use this command.
  deleteWarp:
    usage: </setWarp> <name>
    description: Use this command to delete a public warp point.
    permission: teleportation.deleteWarp
    permission-message: You don't have permission to use this command.
  viewWarps:
    usage: </viewWarps>
    description: Use this command to view all public warp points.
    permission: teleportation.viewWarps
    permission-message: You don't have permission to use this command.
  rtp:
    usage: </rtp>
    description: Use this command to teleport through the world randomly.
    permission: teleportation.rtp
    permission-message: You don't have permission to use this command.
  back:
    usage: </rtp>
    description: Use this command to return to one of your previous locations.
    permission: teleportation.back
    permission-message: You don't have permission to use this command.
  teleport:
    usage: </rtp>
    description: Use this command to teleport to a player.
    permission: teleportation.teleport
    permission-message: You don't have permission to use this command.
  homeInvite:
    usage: </homeInvite> <player name> <home name> 
    description: Use this command to allow a player to use your personal warp point.
    permission: teleportation.homeInvite
    permission-message: You don't have permission to use this command.
  visitHome:
    usage: </rtp>
    description: Use this command to visit a personal warp point of another player.
    permission: teleportation.visitHome
    permission-message: You don't have permission to use this command.
  revokeInvitation:
    usage: </revokeInvitation> <player name> <home name> 
    description: Use this command to remove personal warp point invitation.
    permission: teleportation.revokeInvitation
    permission-message: You don't have permission to use this command.
  setSpawn:
    usage: </setSpawn>
    description: Use this command to create a spawn point.
    permission: teleportation.setSpawn
    permission-message: You don't have permission to use this command.
  spawn:
    usage: </spawn>
    description: Use this command to teleport the spawn point.
    permission: teleportation.spawn
    permission-message: You don't have permission to use this command.
  blockSelector:
    usage: </blockSelecrtor>
    description: Use this command to get the item to create a warp block.
    permission: teleportation.blockSelector
    permission-message: You don't have permission to use this command.
  linkTeleportToBlock:
    usage: </linkTeleportToBlock> <id>
    description: Use this command to a link block with a warp point.
    permission: teleportation.visitHome
    permission-message: You don't have permission to use this command.
  removePortal:
    usage: </removePortal> <warp name>
    description: Use this command remove a warp point from a portal.
    permission: teleportation.visitHome
    permission-message: You don't have permission to use this command.
